server:
  address: 0.0.0.0

spring:
  application:
    name: inventory-service

  output:
    ansi:
      enabled: always

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include:
      - tuning
