tuning:
  scheduler:
    pool-size: 1
  inbox-worker:
    scheduling-interval: ${INBOX_WORKER_SCHEDULING_INTERVAL}
    pool-size: ${INBOX_WORKER_POOL_SIZE}
    limit-size: ${INBOX_WORKER_LIMIT_SIZE}
    retry-max: 3
